# Generated by Django 4.0.4 on 2022-04-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0003_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preprationDuration',
            field=models.DateTimeField(),
        ),
    ]
