# Generated by Django 4.0.4 on 2022-04-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0004_alter_recipe_preprationduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preprationDuration',
            field=models.DurationField(),
        ),
    ]
