# Generated by Django 4.0.4 on 2022-04-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0005_alter_recipe_preprationduration'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='dishType',
            field=models.CharField(choices=[('b', 'Beverages')], default='b', max_length=2),
        ),
    ]
