# Generated by Django 4.0.4 on 2022-04-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0006_recipe_dishtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='dishType',
            field=models.CharField(choices=[('b', 'Beverages'), ('s', 'Starter'), ('m', 'Maincourse'), ('sn', 'Snacks'), ('d', 'Dessert'), ('o', 'Others')], default='b', max_length=2),
        ),
    ]
